// bandeiras emoji por nome de seleção (PT e EN, cobrindo o feed e o mock)
const FLAGS: Record<string, string> = {
  Alemanha: "🇩🇪", Germany: "🇩🇪",
  "Arábia Saudita": "🇸🇦", "Saudi Arabia": "🇸🇦",
  Argélia: "🇩🇿", Algeria: "🇩🇿",
  Argentina: "🇦🇷",
  Austrália: "🇦🇺", Australia: "🇦🇺",
  Áustria: "🇦🇹", Austria: "🇦🇹",
  Bélgica: "🇧🇪", Belgium: "🇧🇪",
  Brasil: "🇧🇷", Brazil: "🇧🇷",
  Camarões: "🇨🇲", Cameroon: "🇨🇲",
  Canadá: "🇨🇦", Canada: "🇨🇦",
  Catar: "🇶🇦", Qatar: "🇶🇦",
  Chile: "🇨🇱",
  Colômbia: "🇨🇴", Colombia: "🇨🇴",
  "Coreia do Sul": "🇰🇷", "South Korea": "🇰🇷",
  "Costa do Marfim": "🇨🇮", "Ivory Coast": "🇨🇮", "Côte d'Ivoire": "🇨🇮",
  "Costa Rica": "🇨🇷",
  Croácia: "🇭🇷", Croatia: "🇭🇷",
  Dinamarca: "🇩🇰", Denmark: "🇩🇰",
  Egito: "🇪🇬", Egypt: "🇪🇬",
  Equador: "🇪🇨", Ecuador: "🇪🇨",
  Escócia: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", Scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  Espanha: "🇪🇸", Spain: "🇪🇸",
  "Estados Unidos": "🇺🇸", USA: "🇺🇸", "United States": "🇺🇸",
  França: "🇫🇷", France: "🇫🇷",
  Gana: "🇬🇭", Ghana: "🇬🇭",
  Holanda: "🇳🇱", Netherlands: "🇳🇱",
  Inglaterra: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  Irã: "🇮🇷", Iran: "🇮🇷",
  Jamaica: "🇯🇲",
  Japão: "🇯🇵", Japan: "🇯🇵",
  Jordânia: "🇯🇴", Jordan: "🇯🇴",
  Marrocos: "🇲🇦", Morocco: "🇲🇦",
  México: "🇲🇽", Mexico: "🇲🇽",
  Nigéria: "🇳🇬", Nigeria: "🇳🇬",
  Noruega: "🇳🇴", Norway: "🇳🇴",
  Panamá: "🇵🇦", Panama: "🇵🇦",
  Paraguai: "🇵🇾", Paraguay: "🇵🇾",
  Peru: "🇵🇪",
  Polônia: "🇵🇱", Poland: "🇵🇱",
  Portugal: "🇵🇹",
  Senegal: "🇸🇳",
  Sérvia: "🇷🇸", Serbia: "🇷🇸",
  Suíça: "🇨🇭", Switzerland: "🇨🇭",
  Tunísia: "🇹🇳", Tunisia: "🇹🇳",
  Ucrânia: "🇺🇦", Ukraine: "🇺🇦",
  Uruguai: "🇺🇾", Uruguay: "🇺🇾",
  Uzbequistão: "🇺🇿", Uzbekistan: "🇺🇿",
  Venezuela: "🇻🇪",
};

export function teamFlag(name: string): string {
  return FLAGS[name] ?? "🏳️";
}
